POST https://infinite-river-65083.herokuapp.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "name" : "Yadadada!!!!", 
    "number": "1234567"
}

###

POST https://infinite-river-65083.herokuapp.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "name" : "Yadadada!!!!"
}

###
POST https://infinite-river-65083.herokuapp.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "number": "1234567"
}

###
POST https://infinite-river-65083.herokuapp.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "name" : "WEEEEEEEE!!!!", 
    "number": "1234567"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name" : "WEEEEEEEE!!!!", 
    "number": "12345678787"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name" : "WEEEEEEEE!!!!"
}